version: "3.8"

services:
  nginx-dev:
    container_name: nginx
    image: nginx:latest
    platform: linux/amd64
    environment:
      APP1_BACKEND: http://app1_backend:5000
      APP1_FRONTEND: http://app1_frontend:3000
      APP2_FRONTEND: http://app2_frontend:4000
    volumes:
      - ./services/predefined/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./services/predefined/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1_backend
      - app1_frontend
      - app2_frontend
    restart: unless-stopped

  postgres:
    image: postgres:17
    platform: linux/amd64
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Strong_P@ssw0rd_2025!
      POSTGRES_DB: postgres
    command: ["postgres", "-N", "1000"]
    volumes:
      - ./services/.nogit/rendered/db/init-db-scriprax.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app1_backend:
    container_name: app1_backend
    image: ghcr.io/kasimmz/child-info:latest
    pull_policy: always
    platform: linux/amd64
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      DATABASE_URL: "postgresql://scriprax_user:Sc5t0m_P@ssw0rd_2025!@postgres:5432/scriprax_db"
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: scriprax_user
      DB_PASSWORD: Sc5t0m_P@ssw0rd_2025!
      DB_DATABASE: scriprax_db
      NODE_ENV: production
      CORS_ORIGIN: "https://api.sciprax.com"
      PORT: 5000
      JWT_SECRET: "your_jwt_secret_here"
      # Fix the path issue - override hardcoded Windows paths
      UPLOAD_BASE_PATH: "/app/uploads"
      VIDEO_UPLOAD_PATH: "/app/videos"
      SCREENSHOT_UPLOAD_PATH: "/app/screenshots"
      UPLOADS_DIR: "/app/uploads"
      # Additional common path environment variables
      VIDEO_DIR: "/app/videos"
      SCREENSHOT_DIR: "/app/screenshots"
      FILES_DIR: "/app/uploads"
    volumes:
      - ./uploads/videos:/app/videos
      - ./uploads/screenshots:/app/screenshots
      - ./uploads:/app/uploads
    user: "1000:1000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  app1_frontend:
    container_name: app1_frontend
    image: ghcr.io/mohamedabuthar/registration-form:latest
    platform: linux/amd64
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BASE_URL: https://api.sciprax.com
      NEXTAUTH_URL: https://api.sciprax.com
      NEXTAUTH_URL_INTERNAL: http://app1_frontend:3000
      NEXTAUTH_TRUST_HOST: "true"
      NEXTAUTH_SECRET: your_nextauth_secret_here
      REACT_APP_API_URL: https://api.sciprax.com/api
      REACT_APP_BACKEND_URL: https://api.sciprax.com/api
      PORT: 3000
    depends_on:
      - app1_backend
    restart: unless-stopped

  app2_frontend:
    container_name: app2_frontend
    image: ghcr.io/kasimmz/child-dashboard:latest
    platform: linux/amd64
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BASE_URL: https://admin.sciprax.com
      PORT: 4000
      REACT_APP_API_URL: https://api.sciprax.com/api
      REACT_APP_BACKEND_URL: https://api.sciprax.com/api
    depends_on:
      - app1_backend
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local